import type { Presentation } from "@/types/presentation";

function colorToHex(color: string): string {
  if (color && color.startsWith("#")) return color.replace("#", "");
  return "0A0A0F";
}

export async function exportToPPTX(presentation: Presentation): Promise<void> {
  // Dynamic import pptxgenjs
  const pptxgen = (await import("pptxgenjs")).default;
  const pptx = new pptxgen();

  pptx.layout = "LAYOUT_16x9";
  pptx.title = presentation.title;
  pptx.subject = "Generated by Nano Banana AI";

  for (const slide of presentation.slides) {
    const pSlide = pptx.addSlide();
    const bgColor = colorToHex(slide.backgroundColor || "#0A0A0F");
    pSlide.background = { color: bgColor };
    const accent = colorToHex(slide.accentColor || "#F5C518");

    if (slide.type === "title") {
      pSlide.addText(slide.title, {
        x: 0.5, y: 1.8, w: 9, h: 1.5,
        fontSize: 40, bold: true, color: "FFFFFF", align: "center",
      });
      if (slide.subtitle) {
        pSlide.addText(slide.subtitle, {
          x: 0.5, y: 3.5, w: 9, h: 0.8,
          fontSize: 18, color: "AAAAAA", align: "center",
        });
      }
      pSlide.addShape(pptx.ShapeType.rect, {
        x: 3.5, y: 4.6, w: 3, h: 0.04, fill: { color: accent },
      });
    } else if (slide.type === "agenda") {
      pSlide.addText(slide.title, { x: 0.5, y: 0.4, w: 9, h: 0.9, fontSize: 28, bold: true, color: "FFFFFF" });
      slide.content.forEach((item, i) => {
        pSlide.addText(`${String(i + 1).padStart(2, "0")}   ${item}`, {
          x: 0.8, y: 1.4 + i * 0.55, w: 8.4, h: 0.5, fontSize: 14, color: "CCCCCC",
        });
      });
    } else if (slide.type === "data") {
      pSlide.addText(slide.title, { x: 0.5, y: 0.4, w: 5, h: 0.9, fontSize: 24, bold: true, color: "FFFFFF" });
      slide.content.forEach((item, i) => {
        pSlide.addText(`• ${item}`, { x: 0.6, y: 1.4 + i * 0.55, w: 4.5, h: 0.5, fontSize: 13, color: "BBBBBB" });
      });
      if (slide.chartData) {
        const rows = [
          slide.chartData.labels.map((l) => ({ text: l, options: { bold: true, color: accent, fontSize: 11 } })),
          slide.chartData.datasets[0].data.map((d) => ({ text: String(d), options: { color: "FFFFFF", fontSize: 11 } })),
        ];
        pSlide.addTable(rows as Parameters<typeof pSlide.addTable>[0], {
          x: 5.2, y: 1.4, w: 4.3, h: 2,
          border: { type: "solid", color: "333333" },
          fill: { color: "111120" },
        });
      }
    } else if (slide.type === "cta") {
      pSlide.addText(slide.title, { x: 0.5, y: 1.5, w: 9, h: 1.4, fontSize: 34, bold: true, color: "FFFFFF", align: "center" });
      if (slide.subtitle) {
        pSlide.addText(slide.subtitle, { x: 0.5, y: 3.1, w: 9, h: 0.6, fontSize: 16, color: "AAAAAA", align: "center" });
      }
      slide.content.forEach((item, i) => {
        pSlide.addText(item, { x: 0.5, y: 3.9 + i * 0.42, w: 9, h: 0.4, fontSize: 13, color: accent, align: "center" });
      });
    } else {
      pSlide.addText(slide.title, { x: 0.5, y: 0.35, w: 9, h: 1, fontSize: 26, bold: true, color: "FFFFFF" });
      pSlide.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.35, w: 1.2, h: 0.04, fill: { color: accent } });
      slide.content.forEach((item, i) => {
        pSlide.addText(`${i + 1}   ${item}`, { x: 0.6, y: 1.55 + i * 0.7, w: 8.8, h: 0.6, fontSize: 14, color: "CCCCCC" });
      });
    }

    if (slide.speakerNotes) pSlide.addNotes(slide.speakerNotes);
    pSlide.addText(`${slide.order} / ${presentation.totalSlides}`, {
      x: 8.5, y: 4.9, w: 1, h: 0.3, fontSize: 9, color: "555555", align: "right",
    });
  }

  await pptx.writeFile({ fileName: `${presentation.title.replace(/\s+/g, "_")}_NanoBanana.pptx` });
}

export async function exportToPDF(presentation: Presentation): Promise<void> {
  const slidesHtml = presentation.slides.map((slide) => `
    <div class="slide" style="background:${slide.backgroundColor};color:#fff;padding:60px;box-sizing:border-box;min-height:100vh;display:flex;flex-direction:column;justify-content:center;page-break-after:always;">
      <h1 style="font-size:2.5em;font-weight:900;margin-bottom:0.5em;color:${slide.accentColor}">${slide.title}</h1>
      ${slide.subtitle ? `<h2 style="font-size:1.2em;color:rgba(255,255,255,0.6);margin-bottom:1em">${slide.subtitle}</h2>` : ""}
      <ul style="list-style:none;padding:0;margin:0">
        ${slide.content.map((c) => `<li style="padding:8px 0;border-bottom:1px solid rgba(255,255,255,0.07);font-size:1em;color:rgba(255,255,255,0.8)">${c}</li>`).join("")}
      </ul>
      ${slide.speakerNotes ? `<div style="margin-top:2em;padding:12px;background:rgba(255,255,255,0.05);border-radius:8px;font-size:0.75em;color:rgba(255,255,255,0.4)">Notes: ${slide.speakerNotes}</div>` : ""}
    </div>`).join("");

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${presentation.title}</title>
  <style>body{margin:0;font-family:'Space Grotesk',Arial,sans-serif;} @media print{.slide{page-break-after:always;}}</style>
  </head><body>${slidesHtml}</body></html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${presentation.title.replace(/\s+/g, "_")}_NanoBanana.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function exportToJSON(presentation: Presentation): Promise<void> {
  const json = JSON.stringify(presentation, null, 2);
  const blob = new Blob([json], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${presentation.title.replace(/\s+/g, "_")}_data.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
