import type { PresetDefinition } from "@/types/presentation";

export const STYLE_PRESETS: PresetDefinition[] = [
  {
    id: "apple",
    name: "Apple Keynote",
    description: "Clean, minimal, and iconic",
    primaryColor: "#FFFFFF",
    accentColor: "#0071E3",
    backgroundColor: "#1D1D1F",
    fontFamily: "SF Pro Display",
    emoji: "🍎",
    tags: ["minimal", "clean", "iconic"],
  },
  {
    id: "startup",
    name: "Startup Pitch Deck",
    description: "Bold, energetic, investor-ready",
    primaryColor: "#F5C518",
    accentColor: "#8B5CF6",
    backgroundColor: "#0A0A0F",
    fontFamily: "Space Grotesk",
    emoji: "🚀",
    tags: ["bold", "energetic", "pitch"],
  },
  {
    id: "ted",
    name: "TED Talk",
    description: "Idea-driven, dramatic, impactful",
    primaryColor: "#FF2B2B",
    accentColor: "#FFFFFF",
    backgroundColor: "#0F0F0F",
    fontFamily: "Georgia",
    emoji: "🎤",
    tags: ["dramatic", "ideas", "impact"],
  },
  {
    id: "minimal",
    name: "Minimal Luxury",
    description: "Elegant, refined, prestigious",
    primaryColor: "#D4AF37",
    accentColor: "#FFFFFF",
    backgroundColor: "#0C0C0C",
    fontFamily: "Playfair Display",
    emoji: "✨",
    tags: ["elegant", "luxury", "gold"],
  },
  {
    id: "glass",
    name: "Glassmorphism",
    description: "Futuristic, translucent, depth",
    primaryColor: "#06B6D4",
    accentColor: "#8B5CF6",
    backgroundColor: "#080818",
    fontFamily: "Inter",
    emoji: "🔮",
    tags: ["glass", "depth", "modern"],
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    description: "Neon, gritty, high-contrast",
    primaryColor: "#00FF88",
    accentColor: "#FF007A",
    backgroundColor: "#0A0010",
    fontFamily: "Courier New",
    emoji: "⚡",
    tags: ["neon", "edgy", "hacker"],
  },
  {
    id: "academic",
    name: "Academic Research",
    description: "Structured, authoritative, clear",
    primaryColor: "#1E40AF",
    accentColor: "#059669",
    backgroundColor: "#FAFAFA",
    fontFamily: "Times New Roman",
    emoji: "📚",
    tags: ["academic", "research", "formal"],
  },
  {
    id: "corporate",
    name: "Corporate Premium",
    description: "Professional, trustworthy, polished",
    primaryColor: "#1E3A5F",
    accentColor: "#C4A438",
    backgroundColor: "#FFFFFF",
    fontFamily: "Calibri",
    emoji: "💼",
    tags: ["corporate", "trust", "premium"],
  },
  {
    id: "futuristic",
    name: "Futuristic AI",
    description: "Neural, data-driven, visionary",
    primaryColor: "#F5C518",
    accentColor: "#06B6D4",
    backgroundColor: "#050510",
    fontFamily: "Space Grotesk",
    emoji: "🤖",
    tags: ["AI", "future", "neural"],
  },
  {
    id: "dark_neon",
    name: "Dark Neon",
    description: "Vivid, electric, atmospheric",
    primaryColor: "#FF6B35",
    accentColor: "#7C3AED",
    backgroundColor: "#07070F",
    fontFamily: "Rajdhani",
    emoji: "🌃",
    tags: ["neon", "dark", "vivid"],
  },
  {
    id: "brutalist",
    name: "Brutalist Modern",
    description: "Raw, bold, unconventional",
    primaryColor: "#FFFF00",
    accentColor: "#FF0000",
    backgroundColor: "#000000",
    fontFamily: "Impact",
    emoji: "🏗️",
    tags: ["bold", "raw", "art"],
  },
  {
    id: "ethiopian",
    name: "Ethiopian Heritage",
    description: "Rich, colorful, culturally vibrant",
    primaryColor: "#009A44",
    accentColor: "#FCDD09",
    backgroundColor: "#1A0A00",
    fontFamily: "Space Grotesk",
    emoji: "🇪🇹",
    tags: ["culture", "heritage", "vibrant"],
  },
  {
    id: "investor",
    name: "Investor Presentation",
    description: "Data-driven, credible, persuasive",
    primaryColor: "#0EA5E9",
    accentColor: "#10B981",
    backgroundColor: "#040D17",
    fontFamily: "Inter",
    emoji: "📈",
    tags: ["data", "invest", "charts"],
  },
  {
    id: "agency",
    name: "Creative Agency",
    description: "Expressive, creative, dynamic",
    primaryColor: "#F97316",
    accentColor: "#EC4899",
    backgroundColor: "#0F0318",
    fontFamily: "Bebas Neue",
    emoji: "🎨",
    tags: ["creative", "agency", "bold"],
  },
  {
    id: "education",
    name: "Modern Education",
    description: "Engaging, accessible, structured",
    primaryColor: "#4F46E5",
    accentColor: "#06B6D4",
    backgroundColor: "#FFFFFF",
    fontFamily: "Nunito",
    emoji: "🎓",
    tags: ["education", "learn", "clear"],
  },
];

export const PRESENTATION_MODES = [
  { id: "standard", label: "Standard Slides", icon: "📋", description: "Classic presentation format" },
  { id: "investor", label: "Investor Pitch", icon: "💰", description: "Data-driven, compelling narrative" },
  { id: "ted", label: "TED Talk", icon: "🎤", description: "Story-driven, idea-focused" },
  { id: "education", label: "Educational", icon: "🎓", description: "Structured learning flow" },
  { id: "research", label: "Research Defense", icon: "🔬", description: "Academic rigour and depth" },
  { id: "startup", label: "Startup Demo", icon: "🚀", description: "Product-focused pitch" },
  { id: "product", label: "Product Launch", icon: "🌟", description: "Excitement-building reveal" },
];

export const INPUT_TYPES = [
  { id: "prompt", label: "Text Prompt", icon: "✍️", description: "Describe your presentation idea", accept: null },
  { id: "topic", label: "Topic Only", icon: "💡", description: "Just give a topic", accept: null },
  { id: "pdf", label: "PDF Upload", icon: "📄", description: "Upload a PDF document", accept: ".pdf" },
  { id: "docx", label: "DOCX Upload", icon: "📝", description: "Upload a Word document", accept: ".docx,.doc" },
  { id: "research", label: "Research Paper", icon: "🔬", description: "Academic paper analysis", accept: ".pdf" },
  { id: "youtube", label: "YouTube URL", icon: "▶️", description: "Extract from a video", accept: null },
  { id: "website", label: "Website URL", icon: "🌐", description: "Scrape and present content", accept: null },
  { id: "voice", label: "Voice Recording", icon: "🎙️", description: "Transcribe and present", accept: ".mp3,.wav,.m4a" },
  { id: "transcript", label: "Meeting Transcript", icon: "📋", description: "Meeting notes to slides", accept: ".txt" },
  { id: "markdown", label: "Markdown Notes", icon: "📓", description: "Convert MD to slides", accept: ".md" },
];
